name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Trigger an Azure Pipeline to biuld'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://ssw.visualstudio.com/SSW.People'
        azure-pipeline-name: 'SSWConsulting.people.ssw.com.au' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
