name: Trigger-DevOps-Build
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger Staging'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://ssw.visualstudio.com/SSW.People'
        azure-pipeline-name: 'Staging' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'

    - name: 'Trigger Production'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://ssw.visualstudio.com/SSW.People'
        azure-pipeline-name: 'Production' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
